# Generated by Django 3.0.3 on 2020-03-19 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200319_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.FilePathField(path='/img'),
        ),
        migrations.AlterModelTable(
            name='product',
            table='products',
        ),
    ]
