# Generated by Django 3.0.3 on 2020-03-19 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20200319_2219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='aciklama',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='title',
            new_name='urunismi',
        ),
        migrations.RemoveField(
            model_name='product',
            name='technology',
        ),
        migrations.AddField(
            model_name='product',
            name='fiyat',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='kategori',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='marka',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
