# Generated by Django 3.0.3 on 2020-03-20 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20200320_0057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='kategori',
            new_name='genel',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='urunismi',
            new_name='isim',
        ),
    ]
