# Generated by Django 3.0.3 on 2020-03-20 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_tur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tur',
            field=models.CharField(max_length=40),
        ),
    ]
