# Generated by Django 3.0.3 on 2020-03-20 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20200320_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='aciklama',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='fiyat',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='genel',
            field=models.CharField(max_length=51),
        ),
        migrations.AlterField(
            model_name='product',
            name='isim',
            field=models.CharField(max_length=101),
        ),
        migrations.AlterField(
            model_name='product',
            name='marka',
            field=models.CharField(max_length=51),
        ),
        migrations.AlterField(
            model_name='product',
            name='tur',
            field=models.CharField(max_length=50),
        ),
    ]
